-- إضافة صور نموذجية من مخزن az_gallery
INSERT INTO public.gallery_images (title, description, category, image_url, thumbnail_url, is_featured, tags, display_order) VALUES
  ('مشروع صيانة متكامل', 'صيانة شاملة لمبنى سكني', 'مشاريع', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/projects/1758966955573%20(1).jpeg', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/projects/1758966955573%20(1).jpeg', true, ARRAY['صيانة', 'مشاريع', 'سكني'], 1),
  ('أعمال السباكة', 'تركيب وصيانة أنظمة السباكة', 'سباكة', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/plumbing/sample1.jpeg', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/plumbing/sample1.jpeg', false, ARRAY['سباكة', 'تركيبات'], 2),
  ('أعمال الكهرباء', 'تمديد الكهرباء وتركيب اللوحات', 'كهرباء', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/electrical/sample1.jpeg', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/electrical/sample1.jpeg', false, ARRAY['كهرباء', 'تركيبات'], 3),
  ('أعمال الدهانات', 'دهان داخلي وخارجي', 'دهانات', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/painting/sample1.jpeg', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/painting/sample1.jpeg', false, ARRAY['دهانات', 'ديكور'], 4),
  ('تركيب السيراميك', 'تركيب وتجديد السيراميك والبورسلين', 'تركيبات', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/tiles/sample1.jpeg', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/tiles/sample1.jpeg', true, ARRAY['سيراميك', 'تركيبات'], 5),
  ('صيانة المكيفات', 'تركيب وصيانة أجهزة التكييف', 'تكييف', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/ac/sample1.jpeg', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/ac/sample1.jpeg', false, ARRAY['تكييف', 'صيانة'], 6),
  ('أعمال النجارة', 'تركيب وتصنيع الأبواب والنوافذ', 'نجارة', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/carpentry/sample1.jpeg', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/carpentry/sample1.jpeg', false, ARRAY['نجارة', 'تركيبات'], 7),
  ('عزل الأسطح', 'عزل حراري ومائي للأسطح', 'عزل', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/insulation/sample1.jpeg', 'https://zrrffsjbfkphridqyais.supabase.co/storage/v1/object/public/az_gallery/insulation/sample1.jpeg', false, ARRAY['عزل', 'أسطح'], 8);