// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shindkpwyxpsexhhfsyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoaW5ka3B3eXhwc2V4aGhmc3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDg2MTMsImV4cCI6MjA2ODYyNDYxM30.DqI8t-vaf8siB9Z6VN42Zi5ZLkj6Xf3bYIwcONp4fNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});